name: Bug report
description: Report a bug or unexpected behavior
assignees: kontang5
labels: bug
title: "Bug: "
body:
  - type: input
    id: overview
    attributes:
      label: Overview
      description: Briefly summarize the bug.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Provide step-by-step instructions to reproduce the bug.
      placeholder: |
        1. 
        2.
        3.
        ...
      render: bash
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Outcome
      description: Describe the expected behavior.
      placeholder: |
        Explain what you expected to happen clearly.
        
        Example: "The expected behavior is that [...]"
      render: markdown
    validations:
        required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Include relevant logs, stack traces, or error messages.
      render: bash
      placeholder: |
        # Include relevant code or logs here
    validations:
        required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other context, screenshots, or relevant details.
    validations:
        required: false
