name: Optimization
description: Suggest improvements to performance, efficiency
assignees: kontang5
labels: optimization
title: "Optimization: "
body:
  - type: input
    id: overview
    attributes:
      label: Overview
      description: Briefly summarize the optimization.
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem / Limitation
      description: Describe the inefficiency, bottleneck, or limitation.
      placeholder: |
        Explain the problem clearly.

        Example: "The current algorithm takes O(n²) time on large datasets."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: proposition
    attributes:
      label: Proposition
      description: Describe your proposed improvement or optimization.
      placeholder: |
        Explain the solution and explain why it is reasonable.
        
        Example: "Replace the current algorithm to [...] will reduce runtime from O(n²) to O(n log n)."
      render: markdown
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any benchmarks, profiling results, or related references.
    validations:
      required: false
